2006-07-07  Hans Boehm <Hans.Boehm@hp.com> 	* configure.ac, Makefile.am: Move the atomic_ops.c and atomic_ops_sysdeps.S 	copying hack from Makefile.am to configure.ac.  Include atomic_ops_sysdeps.S 	only if necessary. 	* Makefile.in, configure: regenerate.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -472,7 +472,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libatomic_ops"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT GC_VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CCAS CCASFLAGS AR ac_ct_AR RANLIB ac_ct_RANLIB GC_CFLAGS THREADDLLIBS THREADS_TRUE THREADS_FALSE PTHREADS_TRUE PTHREADS_FALSE DARWIN_THREADS_TRUE DARWIN_THREADS_FALSE WIN32_THREADS_TRUE WIN32_THREADS_FALSE COMPILER_XLC_TRUE COMPILER_XLC_FALSE EXTRA_TEST_LIBS target_all CPLUSPLUS_TRUE CPLUSPLUS_FALSE INCLUDES CXXINCLUDES addobjs addlibs LN_S ECHO CPP EGREP LIBTOOL ENABLE_GCJ_SUPPORT_TRUE ENABLE_GCJ_SUPPORT_FALSE UNWINDLIBS USE_LIBDIR_TRUE USE_LIBDIR_FALSE subdirs USE_INTERNAL_LIBATOMIC_OPS_TRUE USE_INTERNAL_LIBATOMIC_OPS_FALSE atomic_ops_libs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT GC_VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CCAS CCASFLAGS AR ac_ct_AR RANLIB ac_ct_RANLIB GC_CFLAGS THREADDLLIBS THREADS_TRUE THREADS_FALSE PTHREADS_TRUE PTHREADS_FALSE DARWIN_THREADS_TRUE DARWIN_THREADS_FALSE WIN32_THREADS_TRUE WIN32_THREADS_FALSE COMPILER_XLC_TRUE COMPILER_XLC_FALSE EXTRA_TEST_LIBS target_all CPLUSPLUS_TRUE CPLUSPLUS_FALSE INCLUDES CXXINCLUDES addobjs addlibs LN_S ECHO CPP EGREP LIBTOOL ENABLE_GCJ_SUPPORT_TRUE ENABLE_GCJ_SUPPORT_FALSE UNWINDLIBS USE_LIBDIR_TRUE USE_LIBDIR_FALSE subdirs USE_INTERNAL_LIBATOMIC_OPS_TRUE USE_INTERNAL_LIBATOMIC_OPS_FALSE NEED_ATOMIC_OPS_ASM_TRUE NEED_ATOMIC_OPS_ASM_FALSE atomic_ops_libs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4070,6 +4070,7 @@ fi;
 
 INCLUDES=-I${srcdir}/include
 THREADDLLIBS=
+need_atomic_ops_asm=false
 ## Libraries needed to support dynamic loading and/or threads.
 case "$THREADS" in
  no | none | single)
@@ -4218,6 +4219,10 @@ _ACEOF
 _ACEOF
 
 	THREADDLLIBS="-lpthread -lrt"
+	if test "$GCC" != yes; then
+          CFLAGS="$CFLAGS -O"
+          need_atomic_ops_asm=true
+        fi
 	;;
      *-*-irix*)
 	cat >>confdefs.h <<\_ACEOF
@@ -6249,7 +6254,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6252 "configure"' > conftest.$ac_ext
+  echo '#line 6257 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6822,7 +6827,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:6825: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:6830: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8749,7 +8754,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8752 "configure"
+#line 8757 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8847,7 +8852,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8850 "configure"
+#line 8855 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10222,13 +10227,21 @@ echo "$as_me: error: Missig libatomic_ops." >&2;}
 echo "$as_me: Using internal version of libatomic_ops" >&6;}
 
         test -e ${srcdir}/libatomic_ops \
-	|| ln -f -s ${ao_dir} ${srcdir}/libatomic_ops
+	|| ln -s ${ao_dir} ${srcdir}/libatomic_ops
 
 
 subdirs="$subdirs libatomic_ops"
 
 
-        GC_CFLAGS="${GC_CFLAGS} -I \$(top_srcdir)/libatomic_ops/src"
+        test -e ${srcdir}/atomic_ops.c \
+    	|| ln -s ${srcdir}/libatomic_ops/src/atomic_ops.c \
+		 ${srcdir}/atomic_ops.c
+
+    test -e ${srcdir}/atomic_ops_sysdeps.S \
+    	|| ln -s ${srcdir}/libatomic_ops/src/atomic_ops_sysdeps.S \
+		 ${srcdir}/atomic_ops_sysdeps.S
+
+            GC_CFLAGS="${GC_CFLAGS} -I \$(top_srcdir)/libatomic_ops/src"
     maybe_libatomic_ops="libatomic_ops"
 
 fi
@@ -10243,6 +10256,16 @@ if test -n "$maybe_libatomic_ops" -a "$THREADS" != "none"; then
 else
   USE_INTERNAL_LIBATOMIC_OPS_TRUE='#'
   USE_INTERNAL_LIBATOMIC_OPS_FALSE=
+fi
+
+
+
+if test -n "$maybe_libatomic_ops" -a x$need_atomic_ops_asm = xtrue; then
+  NEED_ATOMIC_OPS_ASM_TRUE=
+  NEED_ATOMIC_OPS_ASM_FALSE='#'
+else
+  NEED_ATOMIC_OPS_ASM_TRUE='#'
+  NEED_ATOMIC_OPS_ASM_FALSE=
 fi
 
 
@@ -10464,6 +10487,13 @@ if test -z "${USE_INTERNAL_LIBATOMIC_OPS_TRUE}" && test -z "${USE_INTERNAL_LIBAT
   { { echo "$as_me:$LINENO: error: conditional \"USE_INTERNAL_LIBATOMIC_OPS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"USE_INTERNAL_LIBATOMIC_OPS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${NEED_ATOMIC_OPS_ASM_TRUE}" && test -z "${NEED_ATOMIC_OPS_ASM_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"NEED_ATOMIC_OPS_ASM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"NEED_ATOMIC_OPS_ASM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -11098,6 +11128,8 @@ s,@USE_LIBDIR_FALSE@,$USE_LIBDIR_FALSE,;t t
 s,@subdirs@,$subdirs,;t t
 s,@USE_INTERNAL_LIBATOMIC_OPS_TRUE@,$USE_INTERNAL_LIBATOMIC_OPS_TRUE,;t t
 s,@USE_INTERNAL_LIBATOMIC_OPS_FALSE@,$USE_INTERNAL_LIBATOMIC_OPS_FALSE,;t t
+s,@NEED_ATOMIC_OPS_ASM_TRUE@,$NEED_ATOMIC_OPS_ASM_TRUE,;t t
+s,@NEED_ATOMIC_OPS_ASM_FALSE@,$NEED_ATOMIC_OPS_ASM_FALSE,;t t
 s,@atomic_ops_libs@,$atomic_ops_libs,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
