2009-09-30  Ivan Maidanski <ivmai@mail.ru> (really Petter Urkedal)
	* configure.ac: Rewrite the tests for external or internal
	libatomic_ops.
	* configure.ac: In particular, drop the symbolic links. Add option
	--with-libatomic-ops for forced selection.
	* Makefile.am: Adjust the path of source files from libatomic_ops
	to not use the links.
	* Makefile.am (libgc_la_LIBADD): Add $(ATOMIC_OPS_LIBS). This will
	be empty if we use the bundled AO sources.
	* configure: Regenerate.
	* Makefile.in: Ditto.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libatomic_ops"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT GC_VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CCAS CCASFLAGS AR ac_ct_AR RANLIB ac_ct_RANLIB GC_CFLAGS THREADDLLIBS THREADS_TRUE THREADS_FALSE PTHREADS_TRUE PTHREADS_FALSE DARWIN_THREADS_TRUE DARWIN_THREADS_FALSE WIN32_THREADS_TRUE WIN32_THREADS_FALSE COMPILER_XLC_TRUE COMPILER_XLC_FALSE AVOID_CPP_LIB_TRUE AVOID_CPP_LIB_FALSE extra_ldflags_libgc EXTRA_TEST_LIBS target_all CPLUSPLUS_TRUE CPLUSPLUS_FALSE INCLUDES CXXINCLUDES addobjs addlibs SED EGREP LN_S ECHO CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ENABLE_GCJ_SUPPORT_TRUE ENABLE_GCJ_SUPPORT_FALSE KEEP_BACK_PTRS_TRUE KEEP_BACK_PTRS_FALSE UNWINDLIBS USE_LIBDIR_TRUE USE_LIBDIR_FALSE subdirs USE_INTERNAL_LIBATOMIC_OPS_TRUE USE_INTERNAL_LIBATOMIC_OPS_FALSE NEED_ATOMIC_OPS_ASM_TRUE NEED_ATOMIC_OPS_ASM_FALSE atomic_ops_libs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT GC_VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CCAS CCASFLAGS AR ac_ct_AR RANLIB ac_ct_RANLIB GC_CFLAGS THREADDLLIBS THREADS_TRUE THREADS_FALSE PTHREADS_TRUE PTHREADS_FALSE DARWIN_THREADS_TRUE DARWIN_THREADS_FALSE WIN32_THREADS_TRUE WIN32_THREADS_FALSE COMPILER_XLC_TRUE COMPILER_XLC_FALSE AVOID_CPP_LIB_TRUE AVOID_CPP_LIB_FALSE extra_ldflags_libgc EXTRA_TEST_LIBS target_all CPLUSPLUS_TRUE CPLUSPLUS_FALSE INCLUDES CXXINCLUDES addobjs addlibs SED EGREP LN_S ECHO CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ENABLE_GCJ_SUPPORT_TRUE ENABLE_GCJ_SUPPORT_FALSE KEEP_BACK_PTRS_TRUE KEEP_BACK_PTRS_FALSE UNWINDLIBS USE_LIBDIR_TRUE USE_LIBDIR_FALSE ATOMIC_OPS_LIBS subdirs USE_INTERNAL_LIBATOMIC_OPS_TRUE USE_INTERNAL_LIBATOMIC_OPS_FALSE NEED_ATOMIC_OPS_ASM_TRUE NEED_ATOMIC_OPS_ASM_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1076,6 +1076,8 @@ Optional Packages:
   --with-target-subdir=SUBDIR
                           configuring with a cross compiler
   --with-cross-host=HOST  configuring with a cross compiler
+  --with-libatomic-ops=yes|no|check
+                          Use a pre-installed libatomic_ops? (default: check)
 
 Some influential environment variables:
   CC          C compiler command
@@ -6240,7 +6242,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6243 "configure"' > conftest.$ac_ext
+  echo '#line 6245 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7375,7 +7377,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:7378:" \
+echo "$as_me:7380:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8438,11 +8440,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8441: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8443: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8445: \$? = $ac_status" >&5
+   echo "$as_me:8447: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8706,11 +8708,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8709: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8711: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8713: \$? = $ac_status" >&5
+   echo "$as_me:8715: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8810,11 +8812,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8813: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8815: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8817: \$? = $ac_status" >&5
+   echo "$as_me:8819: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10279,7 +10281,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 10282 "configure"' > conftest.$ac_ext
+    echo '#line 10284 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11176,7 +11178,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11179 "configure"
+#line 11181 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11276,7 +11278,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11279 "configure"
+#line 11281 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13619,11 +13621,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13622: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13624: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13626: \$? = $ac_status" >&5
+   echo "$as_me:13628: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13723,11 +13725,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13726: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13728: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13730: \$? = $ac_status" >&5
+   echo "$as_me:13732: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14259,7 +14261,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 14262 "configure"' > conftest.$ac_ext
+    echo '#line 14264 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15317,11 +15319,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15320: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15322: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15324: \$? = $ac_status" >&5
+   echo "$as_me:15326: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15421,11 +15423,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15424: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15426: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15428: \$? = $ac_status" >&5
+   echo "$as_me:15430: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16870,7 +16872,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 16873 "configure"' > conftest.$ac_ext
+    echo '#line 16875 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -17648,11 +17650,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17651: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17653: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17655: \$? = $ac_status" >&5
+   echo "$as_me:17657: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17916,11 +17918,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17919: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17921: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17923: \$? = $ac_status" >&5
+   echo "$as_me:17925: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18020,11 +18022,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18023: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18025: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18027: \$? = $ac_status" >&5
+   echo "$as_me:18029: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19489,7 +19491,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 19492 "configure"' > conftest.$ac_ext
+    echo '#line 19494 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -21262,9 +21264,24 @@ fi
 
 
 
+# Atomic Ops
+# ----------
 
-atomic_ops_libs=-latomic_ops
-if test "${ac_cv_header_atomic_ops_h+set}" = set; then
+# Do we want to use an external libatomic_ops?  By default use it if it's
+# found.
+
+# Check whether --with-libatomic-ops or --without-libatomic-ops was given.
+if test "${with_libatomic_ops+set}" = set; then
+  withval="$with_libatomic_ops"
+
+else
+  with_libatomic_ops=check
+fi;
+
+# Check for an external libatomic_ops if the answer was yes or check.  If not
+# found, fail on yes, and convert check to no.
+if test x"$with_libatomic_ops" != xno; then
+   if test "${ac_cv_header_atomic_ops_h+set}" = set; then
   echo "$as_me:$LINENO: checking for atomic_ops.h" >&5
 echo $ECHO_N "checking for atomic_ops.h... $ECHO_C" >&6
 if test "${ac_cv_header_atomic_ops_h+set}" = set; then
@@ -21402,57 +21419,42 @@ echo "${ECHO_T}$ac_cv_header_atomic_ops_h" >&6
 
 fi
 if test $ac_cv_header_atomic_ops_h = yes; then
-   { echo "$as_me:$LINENO: Using pre-installed libatomic_ops" >&5
-echo "$as_me: Using pre-installed libatomic_ops" >&6;}
+  :
 else
-   ao_dir=
-    for candidate in ${srcdir}/libatomic_ops*; do
-	case $candidate in
-	    *.tar.gz)
-		;;
-	    *install)
-	    			;;
-	    *)
-		if test -e "$candidate"; then
-		    ao_dir="$candidate"
-		fi
-		;;
-	esac
-    done
-    if test -z "$ao_dir"; then
-	{ { echo "$as_me:$LINENO: error: Missig libatomic_ops." >&5
-echo "$as_me: error: Missig libatomic_ops." >&2;}
+   if test x"$with_libatomic_ops" != xcheck; then
+  { { echo "$as_me:$LINENO: error: A pre-installed libatomic_ops was not found." >&5
+echo "$as_me: error: A pre-installed libatomic_ops was not found." >&2;}
    { (exit 1); exit 1; }; }
-    fi
-    ao_version="${ao_dir#*libatomic_ops-}"
-    { echo "$as_me:$LINENO: Using internal version of libatomic_ops" >&5
-echo "$as_me: Using internal version of libatomic_ops" >&6;}
+fi
 
-        test -e libatomic_ops \
-	|| ln -s ${ao_dir} libatomic_ops
+	with_libatomic_ops=no
+fi
+
+
+fi
+
+
+# Finally, emit the definitions for bundled or pre-installed AO.
+echo "$as_me:$LINENO: checking which libatomic_ops to use" >&5
+echo $ECHO_N "checking which libatomic_ops to use... $ECHO_C" >&6
+if test x"$with_libatomic_ops" != xno; then
+   echo "$as_me:$LINENO: result: pre-installed" >&5
+echo "${ECHO_T}pre-installed" >&6
+    ATOMIC_OPS_LIBS="-latomic_ops"
+
+else
+   echo "$as_me:$LINENO: result: bundled" >&5
+echo "${ECHO_T}bundled" >&6
 
 
 subdirs="$subdirs libatomic_ops"
 
 
-        test -e atomic_ops.c \
-    	|| ln -s libatomic_ops/src/atomic_ops.c \
-		 atomic_ops.c
-
-    test -e atomic_ops_sysdeps.S \
-    	|| ln -s libatomic_ops/src/atomic_ops_sysdeps.S \
-		 atomic_ops_sysdeps.S
-
-            GC_CFLAGS="${GC_CFLAGS} -I libatomic_ops/src"
-    maybe_libatomic_ops="libatomic_ops"
-
 fi
 
 
 
-
-
-if test -n "$maybe_libatomic_ops" -a "$THREADS" != "none"; then
+if test x$with_libatomic_ops = xno -a x"$THREADS" != xnone; then
   USE_INTERNAL_LIBATOMIC_OPS_TRUE=
   USE_INTERNAL_LIBATOMIC_OPS_FALSE='#'
 else
@@ -21462,14 +21464,13 @@ fi
 
 
 
-if test -n "$maybe_libatomic_ops" -a x$need_atomic_ops_asm = xtrue; then
+if test x$with_libatomic_ops = xno -a x$need_atomic_ops_asm = xtrue; then
   NEED_ATOMIC_OPS_ASM_TRUE=
   NEED_ATOMIC_OPS_ASM_FALSE='#'
 else
   NEED_ATOMIC_OPS_ASM_TRUE='#'
   NEED_ATOMIC_OPS_ASM_FALSE=
 fi
-
 
 
 
@@ -22327,12 +22328,12 @@ s,@KEEP_BACK_PTRS_FALSE@,$KEEP_BACK_PTRS_FALSE,;t t
 s,@UNWINDLIBS@,$UNWINDLIBS,;t t
 s,@USE_LIBDIR_TRUE@,$USE_LIBDIR_TRUE,;t t
 s,@USE_LIBDIR_FALSE@,$USE_LIBDIR_FALSE,;t t
+s,@ATOMIC_OPS_LIBS@,$ATOMIC_OPS_LIBS,;t t
 s,@subdirs@,$subdirs,;t t
 s,@USE_INTERNAL_LIBATOMIC_OPS_TRUE@,$USE_INTERNAL_LIBATOMIC_OPS_TRUE,;t t
 s,@USE_INTERNAL_LIBATOMIC_OPS_FALSE@,$USE_INTERNAL_LIBATOMIC_OPS_FALSE,;t t
 s,@NEED_ATOMIC_OPS_ASM_TRUE@,$NEED_ATOMIC_OPS_ASM_TRUE,;t t
 s,@NEED_ATOMIC_OPS_ASM_FALSE@,$NEED_ATOMIC_OPS_ASM_FALSE,;t t
-s,@atomic_ops_libs@,$atomic_ops_libs,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
